### ISSUE TITLE
Hackage CI build fails due to missing C library

### ISSUE THREAD

**Issue by ddssff** [hackage-trustees/bzlib#2]
I don't know what magic is required to make the bzlib C library available during the build, but that magic is missing from this package.  I suppose it is present in zlib, but it did not jump out at me.

**Comment by phadej** [comment]
See https://github.com/haskell/hackage-server/issues/730, https://github.com/haskell/hackage-server/issues/595 but most importantly https://github.com/haskell-infra/hackage-doc-builder-config

Or did you refer to `haskell-ci` ? Then use `apt: ` to install missing system dependencies. See e.g. https://github.com/haskell/zlib/blob/0b71a311327e92a90bb658618896f34bfce17601/cabal.haskell-ci#L1

**Comment by ddssff** [comment]
Sorry I forgot to point to https://hackage.haskell.org/package/bzlib-0.5.1.0/reports/2
